package com.example.analyzer.exporter;

import com.example.analyzer.model.AnalysisResult;
import com.example.analyzer.model.GraphNode;
import com.example.analyzer.model.GraphRelationship;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Exports analysis results to Neo4j-compatible formats.
 */
public class Neo4jExporter {

    private AnalysisResult result;
    private Gson gson;

    public Neo4jExporter(AnalysisResult result) {
        this.result = result;
        this.gson = new GsonBuilder().setPrettyPrinting().create();
    }

    /**
     * Export to Neo4j Cypher script format.
     */
    public void exportToCypher(String outputPath) throws IOException {
        StringBuilder sb = new StringBuilder();

        sb.append("// Neo4j Cypher Script for Java Project Analysis\n");
        sb.append("// Project: ").append(result.getProjectName()).append("\n");
        sb.append("// Generated by Spoon Java Analyzer\n\n");

        // Create constraints
        sb.append("// Create unique constraints\n");
        sb.append("CREATE CONSTRAINT IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;\n\n");

        // Create nodes
        sb.append("// Create nodes\n");
        for (GraphNode node : result.getNodes()) {
            sb.append(generateCreateNodeCypher(node)).append("\n");
        }

        sb.append("\n// Create relationships\n");
        for (GraphRelationship rel : result.getRelationships()) {
            sb.append(generateCreateRelationshipCypher(rel)).append("\n");
        }

        writeToFile(outputPath, sb.toString());
    }

    /**
     * Export to Neo4j CSV import format.
     */
    public void exportToCsv(String outputDir) throws IOException {
        // Export nodes
        StringBuilder nodesCsv = new StringBuilder();
        nodesCsv.append("id:ID,type,name,qualifiedName,properties\n");

        for (GraphNode node : result.getNodes()) {
            nodesCsv.append(String.format("%s,%s,%s,%s,\"%s\"\n",
                    escapeCsv(node.getId()),
                    escapeCsv(node.getType()),
                    escapeCsv(node.getName()),
                    escapeCsv(node.getQualifiedName()),
                    escapeCsv(gson.toJson(node.getProperties()))));
        }

        writeToFile(outputDir + "/nodes.csv", nodesCsv.toString());

        // Export relationships
        StringBuilder relsCsv = new StringBuilder();
        relsCsv.append(":START_ID,:END_ID,type,sourceType,targetType\n");

        for (GraphRelationship rel : result.getRelationships()) {
            relsCsv.append(String.format("%s,%s,%s,%s,%s\n",
                    escapeCsv(rel.getSourceId()),
                    escapeCsv(rel.getTargetId()),
                    escapeCsv(rel.getType()),
                    escapeCsv(rel.getSourceType()),
                    escapeCsv(rel.getTargetType())));
        }

        writeToFile(outputDir + "/relationships.csv", relsCsv.toString());
    }

    /**
     * Export to JSON format compatible with Neo4j.
     */
    public void exportToJson(String outputPath) throws IOException {
        JsonObject root = new JsonObject();
        root.addProperty("projectName", result.getProjectName());
        root.addProperty("projectPath", result.getProjectPath());
        root.addProperty("nodeCount", result.getNodeCount());
        root.addProperty("relationshipCount", result.getRelationshipCount());

        // Add nodes
        JsonArray nodesArray = new JsonArray();
        for (GraphNode node : result.getNodes()) {
            JsonObject nodeObj = new JsonObject();
            nodeObj.addProperty("id", node.getId());
            nodeObj.addProperty("type", node.getType());
            nodeObj.addProperty("name", node.getName());
            nodeObj.addProperty("qualifiedName", node.getQualifiedName());
            nodeObj.add("properties", gson.toJsonTree(node.getProperties()));
            nodesArray.add(nodeObj);
        }
        root.add("nodes", nodesArray);

        // Add relationships
        JsonArray relsArray = new JsonArray();
        for (GraphRelationship rel : result.getRelationships()) {
            JsonObject relObj = new JsonObject();
            relObj.addProperty("id", rel.getId());
            relObj.addProperty("type", rel.getType());
            relObj.addProperty("sourceId", rel.getSourceId());
            relObj.addProperty("targetId", rel.getTargetId());
            relObj.addProperty("sourceType", rel.getSourceType());
            relObj.addProperty("targetType", rel.getTargetType());
            relsArray.add(relObj);
        }
        root.add("relationships", relsArray);

        writeToFile(outputPath, gson.toJson(root));
    }

    private String generateCreateNodeCypher(GraphNode node) {
        StringBuilder sb = new StringBuilder();
        sb.append("MERGE (n:").append(node.getType()).append(" {id: '").append(node.getId()).append("'}) ");
        sb.append("SET n.name = '").append(escapeCypher(node.getName())).append("', ");
        sb.append("n.qualifiedName = '").append(escapeCypher(node.getQualifiedName())).append("'");

        for (Map.Entry<String, Object> prop : node.getProperties().entrySet()) {
            sb.append(", n.").append(prop.getKey()).append(" = ");
            if (prop.getValue() instanceof String) {
                sb.append("'").append(escapeCypher(prop.getValue().toString())).append("'");
            } else if (prop.getValue() instanceof Boolean) {
                sb.append(prop.getValue());
            } else {
                sb.append(prop.getValue());
            }
        }

        sb.append(";");
        return sb.toString();
    }

    private String generateCreateRelationshipCypher(GraphRelationship rel) {
        return String.format(
                "MATCH (source:%s {id: '%s'}), (target:%s {id: '%s'}) " +
                "MERGE (source)-[:%s]->(target);",
                rel.getSourceType(), rel.getSourceId(),
                rel.getTargetType(), rel.getTargetId(),
                rel.getType()
        );
    }

    private String escapeCypher(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("'", "\\'").replace("\"", "\\\"");
    }

    private String escapeCsv(String value) {
        if (value == null) return "";
        return value.replace("\"", "\"\"");
    }

    private void writeToFile(String path, String content) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(path))) {
            writer.write(content);
        }
    }
}
